<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Your Account</name>
   <tag></tag>
   <elementGuidId>c007ca25-5808-4283-a579-8042c0decddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.nav-bb-right > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-backup-backup']/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bdbdd380-d63f-4abd-a4d1-59e96bac8643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/css/homepage.html/ref=nav_bb_ya</value>
      <webElementGuid>005b57e1-d6e0-4d3f-8885-01b4dfbb2be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Account</value>
      <webElementGuid>0c2ff5f8-e8b4-4e23-a6e7-815819c8d3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-backup-backup&quot;)/div[@class=&quot;nav-bb&quot;]/div[@class=&quot;nav-bb-right&quot;]/a[1]</value>
      <webElementGuid>1108f0e8-272b-42f8-b136-1fadce7521f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-backup-backup']/div/div[3]/a</value>
      <webElementGuid>9bd64498-041c-4302-b371-80d8d4e268f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Your Account')]</value>
      <webElementGuid>e811a8ac-f4f7-4dd4-9344-ba24c9ff9986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/css/homepage.html/ref=nav_bb_ya')]</value>
      <webElementGuid>e05b38fa-d0a0-4d35-9531-779767b9f311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>06a17306-91e3-4b41-b90a-e8bcdd8dd9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/css/homepage.html/ref=nav_bb_ya' and (text() = 'Your Account' or . = 'Your Account')]</value>
      <webElementGuid>27fa4fcf-6c7c-4a2d-97ee-3cfc704d5ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
